# Advanced NumPy

## A.1 ndarray Object Internals

In [174]:
import numpy as np
import pandas as pd
rng = np.random.default_rng(seed=12345)


In [4]:
# For example, a 10 × 5 array would have the shape (10, 5):
np.ones((10, 5)).shape

(10, 5)

In [6]:
# A typical (C order) 3 × 4 × 5 array
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

### NumPy Data Type Hierarchy

In [7]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [8]:
np.issubdtype(floats.dtype, np.floating)

True

You can see all of the parent classes of a specific data type by calling the type’s mro
method:

In [9]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

Therefore, we also have:

In [10]:
np.issubdtype(ints.dtype, np.number)

True

## A.2 Advanced Array Manipulation

### Reshaping Arrays

In [12]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:

arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

A multidimensional array can also be reshaped:

In [15]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

One of the passed shape dimensions can be –1, in which case the value used for that
dimension will be inferred from the data:

In [16]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Since an array’s shape attribute is a tuple, it can be passed to reshape, too:

In [17]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [18]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

The opposite operation of reshape from one-dimensional to a higher dimension is
typically known as flattening or raveling:

In [19]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

ravel does not produce a copy of the underlying values if the values in the result
were contiguous in the original array.

The flatten method behaves like ravel except it always returns a copy of the data:

In [22]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

The data can be reshaped or raveled in different orders. This is a slightly nuanced
topic for new NumPy users and is therefore the next subtopic.

### C Versus FORTRAN Order

In [23]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [28]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

There are some convenience functions, like vstack and hstack, for common kinds of
concatenation. The preceding operations could have been expressed as:

In [30]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

split, on the other hand, slices an array into multiple arrays along an axis:

In [34]:
arr = rng.standard_normal((5, 2))
arr

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

In [36]:
first, second, third = np.split(arr, [1, 3])
first

array([[-1.42382504,  1.26372846]])

In [37]:
second

array([[-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465]])

In [38]:
third

array([[-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

#### Stacking helpers: r_ and c_

There are two special objects in the NumPy namespace, r_ and c_, that make stacking
arrays more concise:

In [39]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = rng.standard_normal((3, 2))
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 2.34740965,  0.96849691],
       [-0.75938718,  0.90219827],
       [-0.46695317, -0.06068952]])

In [40]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 2.34740965,  0.96849691,  3.        ],
       [-0.75938718,  0.90219827,  4.        ],
       [-0.46695317, -0.06068952,  5.        ]])

These additionally can translate slices to arrays:

In [41]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

See the docstring for more on what you can do with c_ and r_.
    

### Repeating Elements: tile and repeat

Two useful tools for repeating or replicating arrays to produce larger arrays are the
repeat and tile functions. repeat replicates each element in an array some number
of times, producing a larger array:

In [45]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [46]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

By default, if you pass an integer, each element will be repeated that number of times.
If you pass an array of integers, each element can be repeated a different number of
times:

In [47]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

Multidimensional arrays can have their elements repeated along a particular axis:

In [58]:
arr = rng.standard_normal((2, 2))
arr

array([[-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ]])

In [59]:
arr.repeat(2, axis=0)

array([[-0.07534331, -0.74088465],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [-1.3677927 ,  0.6488928 ]])

Note that if no axis is passed, the array will be flattened first, which is likely not what
you want. Similarly, you can pass an array of integers when repeating a multidimen‐
sional array to repeat a given slice a different number of times:

In [61]:

arr.repeat([2, 3], axis=0)

array([[-0.07534331, -0.74088465],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [-1.3677927 ,  0.6488928 ],
       [-1.3677927 ,  0.6488928 ]])

In [62]:
arr.repeat([2, 3], axis=1)

array([[-0.07534331, -0.07534331, -0.74088465, -0.74088465, -0.74088465],
       [-1.3677927 , -1.3677927 ,  0.6488928 ,  0.6488928 ,  0.6488928 ]])

tile, on the other hand, is a shortcut for stacking copies of an array along an axis.
Visually you can think of it as being akin to “laying down tiles”:

In [63]:
arr

array([[-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ]])

In [64]:
np.tile(arr, 2)

array([[-0.07534331, -0.74088465, -0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 , -1.3677927 ,  0.6488928 ]])

The second argument is the number of tiles; with a scalar, the tiling is made row by
row, rather than column by column. The second argument to tile can be a tuple
indicating the layout of the “tiling”:

In [65]:
arr

array([[-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ]])

In [66]:
np.tile(arr, (2, 1))

array([[-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ]])

In [67]:
np.tile(arr, (3, 2))

array([[-0.07534331, -0.74088465, -0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 , -1.3677927 ,  0.6488928 ],
       [-0.07534331, -0.74088465, -0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 , -1.3677927 ,  0.6488928 ],
       [-0.07534331, -0.74088465, -0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 , -1.3677927 ,  0.6488928 ]])

### Fancy Indexing Equivalents: take and put

As you may recall from Chapter 4, one way to get and set subsets of arrays is by fancy
indexing using integer arrays:

In [70]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

There are alternative ndarray methods that are useful in the special case of making a
selection only on a single axis:

In [71]:
arr.take(inds)

array([700, 100, 200, 600])

In [73]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [74]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

To use take along other axes, you can pass the axis keyword:

In [75]:
inds = [2, 0, 2, 1]
arr = rng.standard_normal((2, 4))
arr

array([[ 0.36105811, -1.95286306,  2.34740965,  0.96849691],
       [-0.75938718,  0.90219827, -0.46695317, -0.06068952]])

In [76]:
arr.take(inds, axis=1)

array([[ 2.34740965,  0.36105811,  2.34740965, -1.95286306],
       [-0.46695317, -0.75938718, -0.46695317,  0.90219827]])

put does not accept an axis argument but rather indexes into the flattened (one-
dimensional, C order) version of the array. Thus, when you need to set elements

using an index array on other axes, it is best to use []-based indexing.

## A.3 Broadcasting

Broadcasting governs how operations work between arrays of different shapes. It can
be a powerful feature, but it can cause confusion, even for experienced users. The
simplest example of broadcasting occurs when combining a scalar value with an
array:

In [77]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

Here we say that the scalar value 4 has been broadcast to all of the other elements in
the multiplication operation.
For example, we can demean each column of an array by subtracting the column
means. In this case, it is necessary only to subtract an array containing the mean of
each column:

In [80]:
arr = rng.standard_normal((4, 3))
arr.mean(0)

array([0.1205802 , 0.24301074, 0.14436756])

In [81]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 1.60415973,  2.37514869,  0.63299379],
       [ 0.708053  , -1.20199905, -1.35375584],
       [-1.53287221,  0.29853609,  0.60757184],
       [-0.77934052, -1.47168573,  0.11319021]])

In [82]:
demeaned.mean(0)

array([ 5.55111512e-17, -1.11022302e-16,  0.00000000e+00])

Even as an experienced NumPy user, I often find myself having to pause and draw
a diagram as I think about the broadcasting rule. Consider the last example and sup‐
pose we wished instead to subtract the mean value from each row. Since arr.mean(0)
has length 3, it is compatible for broadcasting across axis 0 because the trailing
dimension in arr is 3 and therefore matches. According to the rules, to subtract over
axis 1 (i.e., subtract the row mean from each row), the smaller array must have the
shape (4, 1):

In [83]:
arr

array([[ 1.72473993,  2.61815943,  0.77736134],
       [ 0.8286332 , -0.95898831, -1.20938829],
       [-1.41229201,  0.54154683,  0.7519394 ],
       [-0.65876032, -1.22867499,  0.25755777]])

In [85]:
row_means = arr.mean(1)
row_means.shape

(4,)

In [86]:
row_means.reshape((4, 1))

array([[ 1.70675357],
       [-0.44658113],
       [-0.03960193],
       [-0.54329251]])

In [87]:
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([-1.48029737e-16,  3.70074342e-17,  0.00000000e+00,  3.70074342e-17])

### Broadcasting over Other Axes

In [88]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.01798636,  0.91140586, -0.92939222],
       [ 1.27521433, -0.51240718, -0.76280715],
       [-1.37269008,  0.58114876,  0.79154132],
       [-0.11546781, -0.68538247,  0.80085028]])

use the special np.newaxis attribute along with “full” slices to insert the new
axis:

In [89]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [90]:
arr_1d = rng.standard_normal(3)
arr_1d[:, np.newaxis]

array([[ 0.31290292],
       [-0.13081169],
       [ 1.26998312]])

In [91]:
arr_1d[np.newaxis, :]

array([[ 0.31290292, -0.13081169,  1.26998312]])

Thus, if we had a three-dimensional array and wanted to demean axis 2, we would
need to write:

In [92]:
arr = rng.standard_normal((3, 4, 5))
depth_means = arr.mean(2)
depth_means

array([[ 0.04314136,  0.27468984, -0.18852342, -0.20137996],
       [-0.57324159, -0.54671393,  0.11832783, -0.63005577],
       [ 0.09723001,  0.59537117,  0.03307289, -0.6002202 ]])

In [93]:
depth_means.shape

(3, 4)

In [94]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[ 4.44089210e-17, -1.11022302e-17,  8.88178420e-17,
        -1.66533454e-17],
       [ 2.22044605e-17, -4.44089210e-17, -2.22044605e-17,
        -4.44089210e-17],
       [ 4.44089210e-17,  6.66133815e-17,  0.00000000e+00,
         8.88178420e-17]])

### Setting Array Values by Broadcasting

The same broadcasting rule governing arithmetic operations also applies to setting
values via array indexing. In a simple case, we can do things like:

In [97]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

However, if we had a one-dimensional array of values we wanted to set into the
columns of the array, we can do that as long as the shape is compatible:

In [98]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [99]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## A.4 Advanced ufunc Usage

### ufunc Instance Methods

In [102]:
arr = np.arange(10)
np.add.reduce(arr)


np.int64(45)

In [103]:
arr.sum()

np.int64(45)

In [106]:
my_rng = np.random.default_rng(12346) # for reproducibility
arr = my_rng.standard_normal((5, 5))
arr

array([[-0.903889  ,  0.15713146,  0.89761199, -0.76219554, -0.17625556],
       [ 0.05303172, -1.62844028, -0.17753333,  1.96360352,  1.78125478],
       [-0.87971984, -1.69847913, -1.81891091,  0.11895453, -0.44409513],
       [ 0.76911421, -0.03433778,  0.39252776,  0.75891811, -0.07045967],
       [ 1.04984775,  1.02967072, -0.42005533,  0.78626627,  0.96124929]])

In [107]:
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [108]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [110]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

outer performs a pair-wise cross product between two arrays:

In [111]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [112]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

The output of outer will have a dimension that is the concatenation of the dimen‐
sions of the inputs:

In [114]:
x, y = rng.standard_normal((3, 4)), rng.standard_normal(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

The last method, reduceat, performs a “local reduce,” in essence an array “group by”
operation in which slices of the array are aggregated together. It accepts a sequence of
“bin edges” that indicate how to split and aggregate the values:

In [115]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

The results are the reductions (here, sums) performed over arr[0:5], arr[5:8], and
arr[8:]. As with the other methods, you can pass an axis argument:

In [116]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [117]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### Writing New ufuncs in Python

numpy.frompyfunc accepts a Python function along with a specification for the num‐
ber of inputs and outputs. For example, a simple function that adds element-wise
would be specified as:

In [120]:
def add_elements(x, y):
    return x + y

In [121]:
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

Functions created using frompyfunc always return arrays of Python objects, which
can be inconvenient. Fortunately, there is an alternative (but slightly less feature rich)
function, numpy.vectorize, that allows you to specify the output type:

In [122]:
add_them = np.vectorize(add_elements, otypes=[np.float64])

In [123]:
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [125]:
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [128]:
arr = rng.standard_normal(10000)
%timeit add_them(arr, arr)

1.2 ms ± 39.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [129]:
%timeit np.add(arr, arr)

2.67 μs ± 130 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Later in this appendix we’ll show how to create fast ufuncs in Python using the
Numba library.

## A.5 Structured and Record Arrays

You may have noticed up until now that ndarray is a homogeneous data container;
that is, it represents a block of memory in which each element takes up the same
number of bytes, as determined by the data type. On the surface, this would appear
to not allow you to represent heterogeneous or tabular data. A structured array is an
ndarray in which each element can be thought of as representing a struct in C (hence
the “structured” name) or a row in a SQL table with multiple named fields:

In [130]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

There are several ways to specify a structured data type (see the online NumPy
documentation). One typical way is as a list of tuples with (field_name,
field_data_type). Now, the elements of the array are tuple-like objects whose
elements can be accessed like a dictionary:

In [131]:
sarr[0]

np.void((1.5, 6), dtype=[('x', '<f8'), ('y', '<i4')])

In [132]:
sarr[0]['y']

np.int32(6)

The field names are stored in the dtype.names attribute. When you access a field on
the structured array, a strided view on the data is returned, thus copying nothing:

In [133]:
sarr['x']

array([1.5       , 3.14159265])

### Nested Data Types and Multidimensional Fields

When specifying a structured data type, you can additionally pass a shape (as an int
or tuple):

In [134]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In this case, the x field now refers to an array of length 3 for each record:

In [135]:
arr[0]['x']

array([0, 0, 0])

Conveniently, accessing arr['x'] then returns a two-dimensional array instead of a
one-dimensional array as in prior examples:

In [137]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

This enables you to express more complicated, nested structures as a single block of
memory in an array. You can also nest data types to make more complex structures.
Here is an example:

In [138]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [139]:
In [161]: data['y']

array([5, 6], dtype=int32)

In [140]:
In [162]: data['x']['a']

array([1., 3.])

pandas DataFrame does not support this feature in the same way, though it is similar
to hierarchical indexing.

## A.6 More About Sorting

Like Python’s built-in list, the ndarray sort instance method is an in-place sort,
meaning that the array contents are rearranged without producing a new array:

In [144]:
arr = rng.standard_normal(6)
arr.sort()
arr

array([-0.5177884 , -0.28521495, -0.19143386,  0.21602658,  0.44469225,
        1.02182533])

When sorting arrays in place, remember that if the array is a view on a different
ndarray, the original array will be modified:

In [146]:
arr = rng.standard_normal((3, 5))
arr

array([[ 1.64434738,  1.08870076, -0.45767736,  0.08789363, -1.03268783],
       [-0.15497052,  0.68045779, -0.35611199, -0.13137942,  0.85015653],
       [ 2.63898935,  0.95222112,  0.98384516,  0.02374212,  1.05759431]])

In [147]:
arr[:, 0].sort() # Sort first column values in place
arr

array([[-0.15497052,  1.08870076, -0.45767736,  0.08789363, -1.03268783],
       [ 1.64434738,  0.68045779, -0.35611199, -0.13137942,  0.85015653],
       [ 2.63898935,  0.95222112,  0.98384516,  0.02374212,  1.05759431]])

On the other hand, numpy.sort creates a new, sorted copy of an array. Otherwise, it
accepts the same arguments (such as kind) as ndarray’s sort method:

In [148]:
arr = rng.standard_normal(5)
arr

array([-0.8420634 , -0.48165738, -1.27220444,  1.37086531,  0.18302647])

In [149]:
np.sort(arr)

array([-1.27220444, -0.8420634 , -0.48165738,  0.18302647,  1.37086531])

In [150]:
arr

array([-0.8420634 , -0.48165738, -1.27220444,  1.37086531,  0.18302647])

All of these sort methods take an axis argument for independently sorting the sec‐
tions of data along the passed axis:

In [151]:
arr = rng.standard_normal((3, 5))

In [152]:
arr

array([[ 0.1797321 ,  0.21858133,  0.08545345, -0.1334481 ,  0.20418528],
       [-1.13065844, -1.7764914 , -0.9421879 , -0.51055292,  0.96359658],
       [ 1.19648826, -0.04338855,  1.82694788,  0.44931439, -0.2525905 ]])

In [153]:
arr.sort(axis=1)
arr

array([[-0.1334481 ,  0.08545345,  0.1797321 ,  0.20418528,  0.21858133],
       [-1.7764914 , -1.13065844, -0.9421879 , -0.51055292,  0.96359658],
       [-0.2525905 , -0.04338855,  0.44931439,  1.19648826,  1.82694788]])

You may notice that none of the sort methods have an option to sort in descending
order. This is a problem in practice because array slicing produces views, thus not
producing a copy or requiring any computational work. Many Python users are
familiar with the “trick” that for a list of values, values[::-1] returns a list in
reverse order. The same is true for ndarrays:

In [154]:
arr[:, ::-1]

array([[ 0.21858133,  0.20418528,  0.1797321 ,  0.08545345, -0.1334481 ],
       [ 0.96359658, -0.51055292, -0.9421879 , -1.13065844, -1.7764914 ],
       [ 1.82694788,  1.19648826,  0.44931439, -0.04338855, -0.2525905 ]])

### Indirect Sorts: argsort and lexsort

In data analysis you may need to reorder datasets by one or more keys. For example,
a table of data about some students might need to be sorted by last name, then by first
name. This is an example of an indirect sort, and if you’ve read the pandas-related
chapters, you have already seen many higher-level examples. Given a key or keys (an
array of values or multiple arrays of values), you wish to obtain an array of integer
indices (I refer to them colloquially as indexers) that tells you how to reorder the data
to be in sorted order. Two methods for this are argsort and numpy.lexsort. As an
example:

In [155]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [156]:
values[indexer]

array([0, 1, 2, 3, 5])

As a more complicated example, this code reorders a two-dimensional array by its
first row:

In [157]:
arr = rng.standard_normal((3, 5))
arr[0] = values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.53706272,  1.73067333, -0.09408735,  0.05691404, -0.11137131],
       [-0.18492844, -0.04178432,  1.76722579,  1.2709386 ,  1.29018084]])

In [158]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 1.73067333, -0.09408735, -0.11137131,  0.05691404, -0.53706272],
       [-0.04178432,  1.76722579,  1.29018084,  1.2709386 , -0.18492844]])

lexsort is similar to argsort, but it performs an indirect lexicographical sort on
multiple key arrays. Suppose we wanted to sort some data identified by first and last
names:

In [159]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4])

In [160]:
list(zip(last_name[sorter], first_name[sorter]))

[(np.str_('Arnold'), np.str_('Jane')),
 (np.str_('Arnold'), np.str_('Steve')),
 (np.str_('Jones'), np.str_('Bill')),
 (np.str_('Jones'), np.str_('Bob')),
 (np.str_('Walters'), np.str_('Barbara'))]

lexsort can be a bit confusing the first time you use it, because the order in which
the keys are used to order the data starts with the last array passed. Here, last_name
was used before first_name.

### Alternative Sort Algorithms

A stable sorting algorithm preserves the relative position of equal elements. This can
be especially important in indirect sorts where the relative ordering is meaningful:

In [161]:
values = np.array(['2:first', '2:second', '1:first', '1:second',
.....: '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1])

In [162]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

### Partially Sorting Arrays

One of the goals of sorting can be to determine the largest or smallest elements
in an array. NumPy has fast methods, numpy.partition and np.argpartition, for
partitioning an array around the k-th smallest element:

In [163]:
rng = np.random.default_rng(12345)
arr = rng.standard_normal(20)
arr

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,
        2.34740965,  0.96849691, -0.75938718,  0.90219827, -0.46695317,
       -0.06068952,  0.78884434, -1.25666813,  0.57585751,  1.39897899])

In [164]:
np.partition(arr, 3)

array([-1.95286306, -1.42382504, -1.3677927 , -1.25666813, -0.87066174,
       -0.75938718, -0.74088465, -0.46695317, -0.25917323, -0.07534331,
       -0.06068952,  0.36105811,  0.57585751,  0.6488928 ,  0.78884434,
        0.90219827,  0.96849691,  1.26372846,  1.39897899,  2.34740965])

After you call partition(arr, 3), the first three elements in the result are the small‐
est three values in no particular order. numpy.argpartition, similar to numpy.arg
sort, returns the indices that rearrange the data into the equivalent order:

In [165]:
indices = np.argpartition(arr, 3)
indices

array([ 9,  0,  6, 17,  2, 12,  5, 14,  3,  4, 15,  8, 18,  7, 16, 13, 11,
        1, 19, 10])

In [166]:
arr.take(indices)

array([-1.95286306, -1.42382504, -1.3677927 , -1.25666813, -0.87066174,
       -0.75938718, -0.74088465, -0.46695317, -0.25917323, -0.07534331,
       -0.06068952,  0.36105811,  0.57585751,  0.6488928 ,  0.78884434,
        0.90219827,  0.96849691,  1.26372846,  1.39897899,  2.34740965])

### numpy.searchsorted: Finding Elements in a Sorted Array

searchsorted is an array method that performs a binary search on a sorted array,
returning the location in the array where the value would need to be inserted to
maintain sortedness:

In [167]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

np.int64(3)

You can also pass an array of values to get an array of indices back:

In [168]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

You might have noticed that searchsorted returned 0 for the 0 element. This is
because the default behavior is to return the index at the left side of a group of equal
values:

In [169]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])

array([0, 3])

In [170]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

As another application of searchsorted, suppose we had an array of values between
0 and 10,000, and a separate array of “bucket edges” that we wanted to use to bin the
data:

In [171]:
data = np.floor(rng.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([ 815., 1598., 3401., 4651., 2664., 8157., 1932., 1294.,  916.,
       5985., 8547., 6016., 9319., 7247., 8605., 9293., 5461., 9376.,
       4949., 2737., 4517., 6650., 3308., 9034., 2570., 3398., 2588.,
       3554.,   50., 6286., 2823.,  680., 6168., 1763., 3043., 4408.,
       1502., 2179., 4743., 4763., 2552., 2975., 2790., 2605., 4827.,
       2119., 4956., 2462., 8384., 1801.])

To then get a labeling to which interval each data point belongs (where 1 would mean
the bucket [0, 100)), we can simply use searchsorted:

In [172]:
labels = bins.searchsorted(data)
labels

array([2, 3, 3, 3, 3, 4, 3, 3, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 4,
       3, 4, 3, 3, 3, 3, 1, 4, 3, 2, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 3])

This, combined with pandas’s groupby, can be used to bin data:

In [175]:
pd.Series(data).groupby(labels).mean()

1      50.000000
2     803.666667
3    3079.741935
4    7635.200000
dtype: float64

## A.7 Writing Fast NumPy Functions with Numba

To introduce Numba, let’s consider a pure Python function that computes the expres‐
sion (x - y).mean() using a for loop:

In [178]:
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

This function is slow:

In [184]:
x = rng.standard_normal(10_000_000)
y = rng.standard_normal(10_000_000)
%timeit mean_distance(x, y)
%timeit (x - y).mean()

2.33 s ± 40.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
31.1 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [185]:
import numba as nb
numba_mean_distance = nb.jit(mean_distance)

We also could have written this as a decorator:

In [186]:
def numba_mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

The resulting function is actually faster than the vectorized NumPy version:

In [187]:
%timeit numba_mean_distance(x, y)

2.53 s ± 56.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In the previous example, we could have written:

In [189]:
from numba import float64, njit
@njit(float64(float64[:], float64[:]))
def mean_distance(x, y):
    return (x - y).mean()

I encourage you to learn more by reading the online documentation for Numba. The
next section shows an example of creating custom NumPy ufunc objects.

### Creating Custom numpy.ufunc Objects with Numba

The numba.vectorize function creates compiled NumPy ufuncs, which behave

In [190]:
from numba import vectorize
@vectorize
def nb_add(x, y):
    return x + y

In [191]:
x = np.arange(10)
nb_add(x, x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [192]:
nb_add.accumulate(x, 0)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

## A.8 Advanced Array Input and Output

### Memory-Mapped Files

To create a new memory map, use the function np.memmap and pass a file path, data
type, shape, and file mode:

In [194]:
In [217]: mmap = np.memmap('mymmap', dtype='float64', mode='w+',
.....: shape=(10000, 10000))
In [218]: mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

Slicing a memmap returns views on the data on disk:

In [195]:
In [219]: section = mmap[:5]

If you assign data to these, it will be buffered in memory, which means that the
changes will not be immediately reflected in the on-disk file if you were to read
the file in a different application. Any modifications can be synchronized to disk by
calling flush:

In [196]:
section[:] = rng.standard_normal((5, 10000))
mmap.flush()
mmap

memmap([[ 2.3608341 , -0.72844877,  0.59298408, ..., -0.28252701,
         -1.11893958, -0.0867724 ],
        [-0.36832508,  0.55722181,  1.44757705, ...,  0.89213712,
         -0.80727279,  2.37897524],
        [-0.16908566, -0.49004449, -0.97269951, ..., -0.96584464,
         -0.39431253, -0.45955889],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [197]:
del mmap

Whenever a memory map falls out of scope and is garbage collected, any changes
will be flushed to disk also. When opening an existing memory map, you still have to
specify the data type and shape, as the file is only a block of binary data without any
data type information, shape, or strides:

In [200]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

memmap([[ 2.3608341 , -0.72844877,  0.59298408, ..., -0.28252701,
         -1.11893958, -0.0867724 ],
        [-0.36832508,  0.55722181,  1.44757705, ...,  0.89213712,
         -0.80727279,  2.37897524],
        [-0.16908566, -0.49004449, -0.97269951, ..., -0.96584464,
         -0.39431253, -0.45955889],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

## A.9 Performance Tips

### The Importance of Contiguous Memory

These properties can be explicitly checked via the flags attribute on the ndarray:

In [204]:
arr_c = np.ones((100, 10000), order='C')
arr_f = np.ones((100, 10000), order='F')
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [205]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [206]:
arr_f.flags.f_contiguous

True

In this example, summing the rows of these arrays should, in theory, be faster for
arr_c than arr_f since the rows are contiguous in memory. Here, I check using
%timeit in IPython (these results may differ on your machine):

In [207]:
%timeit arr_c.sum(1)

333 μs ± 11.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [208]:
%timeit arr_f.sum(1)

281 μs ± 10.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)



When you’re looking to squeeze more performance out of NumPy, this is often a
place to invest some effort. If you have an array that does not have the desired
memory order, you can use copy and pass either 'C' or 'F':

In [209]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

When constructing a view on an array, keep in mind that the result is not guaranteed
to be contiguous:

In [210]:
arr_c[:50].flags.contiguous

True

In [211]:
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

# END

In [212]:
!jupyter nbconvert --to html "codes".ipynb

[NbConvertApp] Converting notebook codes.ipynb to html
[NbConvertApp] Writing 546530 bytes to codes.html
